version: "3.9"
services:
  checkpoint-bot:
    image: ${RATE_BOT_IMAGE}
    profiles:
      - "dynamic-rate"
    volumes:
      - ./accounts:/accounts/
      - artifacts:/artifacts/

volumes:
  artifacts:
