services:

  frontend:
    image: ${FRONTEND_IMAGE}
    profiles:
      - "frontend"
    environment:
      - VITE_CUSTOM_CHAIN_NODE_RPC_URL=${UI_RPC_URL}
      - VITE_CUSTOM_CHAIN_ADDRESSES_URL=${UI_ADDRESSES_URL}
      - VITE_CUSTOM_CHAIN_CHAIN_ID=${UI_CHAIN_ID}
      - VITE_WALLET_CONNECT_PROJECT_ID=${UI_WALLET_CONNECT_PROJECT_ID}
      - VITE_CAPSULE_API_KEY=${UI_CAPSULE_API_KEY}
      - VITE_CAPSULE_ENV=${UI_CAPSULE_ENV}
    command: "yarn workspace hyperdrive-trading dev --host 0.0.0.0"
