version: "3.9"
services:
  ethereum:
    image: ${DEVNET_IMAGE}
    # without --block-time we're in "automine" mode and blocks are mined
    # as soon as transactions are received, or with manual commands.
    # this is "hecking fast" mode.
    command: |
      'anvil --load-state ./data --host 0.0.0.0 --code-size-limit 9999999999 --chain-id ${CHAIN_ID}'
    volumes:
      - artifacts:/src/artifacts/

  # Mine the first block to prevent overflow/underflow errors on the first
  # read calls.
  mine:
    image: curlimages/curl:latest
    command: |
      /bin/sh -c "sleep 2; curl -X POST -H \"Content-Type: application/json\" --data '{\"jsonrpc\":\"2.0\", \"method\":\"anvil_mine\", \"params\":[], \"id\":1}' ${RPC_URI}"

  # Set the block timestamp interval
  timestamp_interval:
    image: curlimages/curl:latest
    profiles:
      - "competition"
    command: |
      /bin/sh -c "sleep 5; curl -X POST -H \"Content-Type: application/json\" --data '{\"jsonrpc\":\"2.0\", \"method\":\"anvil_setBlockTimestampInterval\", \"params\":[${BLOCK_TIMESTAMP_INTERVAL}], \"id\":1}' ${RPC_URI}"

  # Set account balances
  fund-accounts:
    image: ${FUND_ACCOUNTS_IMAGE}
    profiles:
      - "fund-accounts"
    volumes:
      - ./accounts:/accounts/
      - artifacts:/artifacts/

  artifacts:
    image: ${ARTIFACTS_IMAGE}
    volumes:
      - artifacts:/var/www/artifacts/

  checkpoint-bot:
    image: ${ELFPY_IMAGE}
    command: |
      /bin/sh -c "sleep 1; python lib/agent0/bin/checkpoint_bot.py"
    env_file:
      - .env

volumes:
  artifacts:
