services:
  anvil:
    image: ${FORK_IMAGE}
    command: |
      'anvil --fork-url ${MAINNET_RPC_URL} --chain-id 42069 --host 0.0.0.0'
    ports:
      - 8545:8545
    env_file:
      - .env
    networks:
      - fork

  deployer:
    image: ${FORK_IMAGE}
    command: |
      'make deploy-fork'
    restart: on-failure
    env_file:
      - .env
    volumes:
      - artifacts:/src/artifacts/
    networks:
      - fork

  artifacts:
    image: ${FORK_IMAGE}
    volumes:
      - artifacts:/var/www/artifacts/
    depends_on:
      deployer:
        condition: service_completed_successfully
    networks:
      - fork

  checkpoint-bot:
    image: ${FORK_IMAGE}
    command: |
      'cp /src/artifacts/deployments.local.json /src/deployments.local.json && npx hardhat fork:create-checkpoints --network mainnet_fork --config hardhat.config.mainnet_fork.ts --show-stack-traces'
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - artifacts:/src/artifacts/
    depends_on:
      deployer:
        condition: service_completed_successfully
    networks:
      - fork

  rate-bot:
    image: ${FORK_IMAGE}
    command: |
      'cp /src/artifacts/deployments.local.json /src/deployments.local.json && npx hardhat fork:maintain-rate --network mainnet_fork --config hardhat.config.mainnet_fork.ts --show-stack-traces'
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - artifacts:/src/artifacts/
    depends_on:
      deployer:
        condition: service_completed_successfully
    networks:
      - fork

volumes:
  artifacts:

networks:
  fork:
