version: "3.9"
services:
  # TODO make single container for all pools
  fuzz-erc4626:
    image: ${AGENT0_IMAGE}
    profiles:
      - "fuzz"
    working_dir: /app/
    command: /bin/sh -c "DEVELOP=true python scripts/fuzz_bots.py --pool erc4626_hyperdrive"
    env_file:
      - .env
    volumes:
      - .crash_report:/app/.crash_report

  fuzz-invariant-check-erc4626:
    image: ${AGENT0_IMAGE}
    profiles:
      - "fuzz"
    working_dir: /app/
    command: /bin/sh -c "python scripts/fuzz_bot_invariant_checks.py --pool erc4626_hyperdrive"
    env_file:
      - .env
    volumes:
      - .crash_report:/app/.crash_report

  fuzz-steth:
    image: ${AGENT0_IMAGE}
    profiles:
      - "fuzz"
    working_dir: /app/
    command: /bin/sh -c "DEVELOP=true python scripts/fuzz_bots.py --pool steth_hyperdrive"
    env_file:
      - .env
    volumes:
      - .crash_report:/app/.crash_report

  fuzz-invariant-check-steth:
    image: ${AGENT0_IMAGE}
    profiles:
      - "fuzz"
    working_dir: /app/
    command: /bin/sh -c "python scripts/fuzz_bot_invariant_checks.py --pool steth_hyperdrive"
    env_file:
      - .env
    volumes:
      - .crash_report:/app/.crash_report
