version: "3.9"
services:
  ethereum:
    image: ghcr.io/foundry-rs/foundry
    command: |
      'anvil --accounts 30 --block-time 12 --host 0.0.0.0'
  migrations:
    image: ghcr.io/delvtech/hyperdrive/migrations:nightly-ce5ae99cfdc0546059e20081311558a28f8fb679
    environment:
      - ETH_FROM=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - PRIVATE_KEY=ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - RPC_URL=http://ethereum:8545
    volumes:
      - artifacts:/src/artifacts/
    # TODO: This is a band-aid solution for the memory leaks experienced on
    # Apple Silicon. Remove the restart policy when this reliably starts.
    restart: on-failure:5
  artifacts:
    image: ghcr.io/delvtech/infra/artifacts:nightly-9b5cd7b753e578ce7b538d5458134f022574d1eb
    volumes:
      - artifacts:/var/www/artifacts/
volumes:
  artifacts:
