version: "3.9"
services:
  fuzz:
    image: ${AGENT0_IMAGE}
    profiles:
      - "fuzz"
    working_dir: /app/
    command: /bin/sh -c "DEVELOP=true python scripts/fuzz_bots.py"
    env_file:
      - .env
    volumes:
      - .crash_report:/app/.crash_report

  fuzz-invariant-check:
    image: ${AGENT0_IMAGE}
    profiles:
      - "fuzz"
    working_dir: /app/
    command: /bin/sh -c "python scripts/fuzz_bot_invariant_checks.py"
    env_file:
      - .env
    volumes:
      - .crash_report:/app/.crash_report
