version: "3.9"
services:

  bot:
    # 2022-05-31 afer "generalized bot settings working with FixedPoint" (#484)
    # image: ghcr.io/delvtech/elf-simulations/elf-sims:nightly-2ef72dd9879511d639695b83b35fb2463b6b2ca6
    # local elf-sims pointing to IHyperdrive
    # image: elf-sims:${ELFPY_TAG}
    image: ghcr.io/delvtech/elf-simulations/elf-sims:${ELFPY_TAG}
    profiles:
      - "bots"
    working_dir: /app/
    environment:
      - BOT_ALCHEMY=false
      - HALT_ON_ERRORS=false
      - BOT_ARTIFACTS_URL=http://artifacts:80
      - BOT_DEVNET=true
      - BOT_LOG_FILENAME=testnet_bots
      - BOT_LOG_LEVEL=INFO
      # TODO get default value for this
      - BOT_MAX_BYTES=100
      - BOT_NUM_LOUIE=0
      - BOT_NUM_FRIDA=0
      - BOT_NUM_RANDOM=4
      - BOT_TRADE_CHANCE=0.1
      - BOT_RPC_URL=http://ethereum:8545

    command: "/bin/sh -c 'python elfpy/bots/bots_server.py examples/evm_bots.py'"

volumes:
  artifacts:
