version: "3.9"
services:

  data:
    image: ghcr.io/delvtech/elf-simulations/elf-simulations:${ELFPY_TAG}
    profiles:
      - "data"
    working_dir: /app/
    command: /bin/sh -c "python elfpy/data/acquire_data.py"
    # This file sets postgres information
    env_file:
      - .env
    # These environment variables are connecting to other necessary containers
    depends_on:
      - ethereum
      - artifacts
    environment:
      - CONTRACTS_URL=http://artifacts:${ARTIFACT_PORT}/addresses.json
      - ETHEREUM_NODE=http://ethereum:${ETH_PORT}

    deploy:
      resources:
          limits:
            cpus: "0"
            memory: "0"

  username-reg:
    image: ghcr.io/delvtech/elf-simulations/elf-simulations:${ELFPY_TAG}
    profiles:
      - "data"
    working_dir: /app/
    command: /bin/sh -c "python elfpy/data/register_username_server.py"
    # This file sets postgres information
    env_file:
      - .env
    deploy:
      resources:
          limits:
            cpus: "0"
            memory: "0"

volumes:
  artifacts:
