version: "3.9"
services:

  ethereum:
    image: ghcr.io/delvtech/hyperdrive/devnet:${HYPERDRIVE_TAG}
    # without --block-time we're in "automine" mode and blocks are mined
    # as soon as transactions are received, or with manual commands.
    # this is "hecking fast" mode.
    command: |
      'anvil --load-state ./data --host 0.0.0.0 '
    volumes:
      - artifacts:/src/artifacts/

  artifacts:
    image: ghcr.io/delvtech/infra/artifacts:${ARTIFACTS_TAG}
    volumes:
      - artifacts:/var/www/artifacts/

volumes:
  artifacts:
