version: "3.9"
services:

# TODO also add acquire_data in this compose file as well
  username-reg:
    image: ghcr.io/delvtech/elf-simulations/elf-simulations:${ELFPY_TAG}
    profiles:
      - "data"
    working_dir: /app/
    command: /bin/sh -c "python elfpy/data/register_username_server.py"
    env_file:
      - .env
    deploy:
      resources:
          limits:
            cpus: "0"
            memory: "0"

volumes:
  artifacts:
