version: "3.9"
services:

  data:
    image: ${ELFPY_IMAGE}
    profiles:
      - "data"
    working_dir: /app/
    command: /bin/sh -c "python lib/chainsync/bin/run_chainsync.py"
    env_file:
      - .env

  username-reg:
    image: ${ELFPY_IMAGE}
    profiles:
      - "data"
    working_dir: /app/
    command: /bin/sh -c "python lib/chainsync/bin/register_username_server.py"
    env_file:
      - .env

  dashboard:
    image: ${ELFPY_IMAGE}
    profiles:
      - "data"
    working_dir: /app/
    command: /bin/sh -c "streamlit run lib/chainsync/bin/run_hyperdrive_dashboard.py \
               --server.port=8501 --server.headless true\
               --server.fileWatcherType=none --browser.gatherUsageStats=false"
    env_file:
      - .env


volumes:
  artifacts:
