version: "3.9"
services:

  hyperdrive-monorepo:
    image: ghcr.io/delvtech/hyperdrive-monorepo/hyperdrive-monorepo:${HYPERDRIVE_MONOREPO_TAG}
    profiles:
      - "frontend"
    environment:
      - VITE_ALCHEMY_GOERLI_RPC_KEY=${ALCHEMY_GOERLI_API_KEY}
      - VITE_LOCALHOST_NODE_RPC_URL=http://ethereum:${ETH_PORT}
      - VITE_LOCALHOST_ADDRESSES_URL=http://artifacts:${ARTIFACT_PORT}
    command: "yarn workspace hyperdrive-trading dev --host 0.0.0.0"
