version: "3.9"
services:

  bot:
    # 2022-05-31 afer "generalized bot settings working with FixedPoint" (#484)
    # image: ghcr.io/delvtech/elf-simulations/elf-sims:nightly-2ef72dd9879511d639695b83b35fb2463b6b2ca6
    # local elf-sims pointing to IHyperdrive
    # image: elf-sims:${ELFPY_TAG}
    image: elf-sims:latest
    profiles:
      - "bots"
    working_dir: /app/
    command: |
      /bin/sh -c "
        echo 'Starting bot...' &&
        python -c 'from elfpy.bots import BotConfig; config = BotConfig(); config.artifacts_url = \"http://artifacts:80\"; config.rpc_url = \"http://ethereum:8545\"; config.log_filename=\"docker-bot\"; config.log_file_and_stdout=True; config.save_as_json(\"docker-config.json\")' &&
        cat docker-config.json &&
        curl --verbose --include -H \"Content-Type: application/json\" -d @docker-config.json http://botserver:5000/run_script
      "
    volumes:
      - artifacts:/app/artifacts
    depends_on:
      - botserver
      - artifacts

volumes:
  artifacts:
