version: "3.9"
services:
  ethereum:
    image: ghcr.io/delvtech/hyperdrive/devnet:${HYPERDRIVE_TAG}
    # without --block-time we're in "automine" mode and blocks are mined
    # as soon as transactions are received, or with manual commands.
    # this is "hecking fast" mode.
    command: |
      'anvil --load-state ./data --host 0.0.0.0 --chain-id ${CHAIN_ID}'
    volumes:
      - artifacts:/src/artifacts/

  # Mine the first block to prevent overflow/underflow errors on the first
  # read calls.
  mine:
    image: curlimages/curl:latest
    depends_on:
      - ethereum
    command: |
      /bin/sh -c "sleep 1; curl -X POST -H \"Content-Type: application/json\" --data '{\"jsonrpc\":\"2.0\", \"method\":\"anvil_mine\", \"params\":[], \"id\":1}' http://ethereum:8545"

  # Set account balances
  fund-accounts:
    image: ghcr.io/delvtech/infra/fund-accounts:${INFRA_TAG}
    profiles:
      - "fund-accounts"
    depends_on:
      - ethereum
    volumes:
      - ./accounts:/accounts/
      - artifacts:/artifacts/

  artifacts:
    image: ghcr.io/delvtech/infra/artifacts:${INFRA_TAG}
    volumes:
      - artifacts:/var/www/artifacts/

  checkpoint-bot:
    image: ghcr.io/delvtech/elf-simulations/elf-simulations:${ELFPY_TAG}
    depends_on:
      - ethereum
    command: |
      /bin/sh -c "sleep 1; ARTIFACTS_URL=$ARTIFACTS_URL RPC_URL=$RPC_URL python elfpy/bots/checkpoint_bot.py"

volumes:
  artifacts:
