version: "3.9"
services:

  bots:
    image: ghcr.io/delvtech/elf-simulations/elf-simulations:${ELFPY_TAG}
    profiles:
      - "bots"
    working_dir: /app/
    command: /bin/sh -c "python elfpy/bots/bot_server.py examples/evm_bots.py"
    deploy:
      resources:
          limits:
            cpus: "0"
            memory: "0"

volumes:
  artifacts:
