version: "3.9"
services:

  hyperdrive-monorepo:
    image: ghcr.io/delvtech/hyperdrive-monorepo/hyperdrive-monorepo:${HYPERDRIVE_MONOREPO_TAG}
    profiles:
      - "frontend"
    environment:
      - VITE_CUSTOM_CHAIN_NODE_RPC_URL=${UI_RPC_URL}
      - VITE_CUSTOM_CHAIN_ADDRESSES_URL=${UI_ADDRESSES_URL}
      - VITE_CUSTOM_CHAIN_CHAIN_ID=${UI_CHAIN_ID}
      - VITE_ALCHEMY_GOERLI_RPC_KEY=${UI_ALCHEMY_GOERLI_RPC_KEY}
      - VITE_WALLET_CONNECT_PROJECT_ID=${UI_WALLET_CONNECT_PROJECT_ID}
    command: "yarn workspace hyperdrive-trading dev --host 0.0.0.0"
