name: Publish the artifacts and fund-accounts images

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ghcr.io/${{ github.repository }}

jobs:
  push-artifacts-image:
    uses: ./.github/workflows/publish-image.yml
    with:
      name: artifacts
      context: ./containers/artifacts

  push-fund-accounts-image:
    uses: ./.github/workflows/publish-image.yml
    with:
      name: fund-accounts
      context: ./containers/fund-accounts
