name: Publish the artifacts and fund-accounts images

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  push-artifacts-image:
    uses: ./.github/workflows/publish-image.yml
    with:
      name: artifacts
      context: ./images/artifacts

  push-fund-accounts-image:
    uses: ./.github/workflows/publish-image.yml
    with:
      name: fund-accounts
      context: ./images/fund-accounts

  push-rate-bot-image:
    uses: ./.github/workflows/publish-image.yml
    with:
      name: rate-bot
      context: ./images/rate-bot
