name: Publish the artifacts and fund-accounts images

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ghcr.io/${{ github.repository }}

jobs:
  push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for artifacts image
        id: artifacts_meta
        uses: docker/metadata-action@v4.5.0
        with:
          images: ${{ env.IMAGE_PATH }}/artifacts
          tags: |
            # Add a version tag when a valid semver tag is pushed.
            type=semver,pattern={{version}}
            # Add the edge tag to every image to represent the latest commit to main
            type=raw,value=edge,enable={{is_default_branch}}

      - name: Build and push artifacts image
        uses: docker/build-push-action@v4.1.0
        with:
          context: ./services/artifacts
          push: true
          tags: ${{ steps.artifacts_meta.outputs.tags }}
          labels: ${{ steps.artifacts_meta.outputs.labels }}

      - name: Extract metadata (tags, labels) for fund-accounts image
        id: fund_accounts_meta
        uses: docker/metadata-action@v4.5.0
        with:
          images: ${{ env.IMAGE_PATH }}/fund-accounts
          tags: |
            # Add a version tag when a valid semver tag is pushed.
            type=semver,pattern={{version}}
            # Add the edge tag to every image to represent the latest commit to main
            type=raw,value=edge,enable={{is_default_branch}}

      - name: Build and push fund-accounts image
        uses: docker/build-push-action@v4.1.0
        with:
          context: ./services/fund-accounts
          push: true
          tags: ${{ steps.fund_accounts_meta.outputs.tags }}
          labels: ${{ steps.fund_accounts_meta.outputs.labels }}
