name: Run test

on:
  workflow_call:
    inputs:
      name:
        description: The name of the file in the /test directory to run (without the extension)
        type: string
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup env
        run: bash ./setup_env.sh --all

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run test
        run: |
          source .env
          bash ./test/${{ inputs.name }}.sh
