name: Test container changes

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  # Check if any files in the /containers directory were changed in this PR
  detect-changes:
    uses: ./.github/workflows/check-diff.yaml
    with:
      pattern: ^containers/

  test-containers:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    uses: ./.github/workflows/run-test.yaml
    with:
      name: test_containers
