name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      # Run the `./setup_env.sh` script with `--all`. The test fails if this
      # exits with a non-zero error code.
      - name: test setup_env.sh
        run: ./setup_env.sh --all

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker-compose stack
        run: |
          source .env
          docker compose up -d

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Check services
        run: docker compose ps -a
